// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwQdW5JSkuGCCzq-2g0Y4GtRcw_nDLKk',
    appId: '1:558171062775:web:796fdc5cf2c5591f8f2ef2',
    messagingSenderId: '558171062775',
    projectId: 'quickhub-f3b02',
    authDomain: 'quickhub-f3b02.firebaseapp.com',
    storageBucket: 'quickhub-f3b02.firebasestorage.app',
    measurementId: 'G-R5PZBT8TPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArj_3TC6KPHwHKNOYA4N7NRi-75fXaQZ8',
    appId: '1:558171062775:android:097007d84873eb718f2ef2',
    messagingSenderId: '558171062775',
    projectId: 'quickhub-f3b02',
    storageBucket: 'quickhub-f3b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4EK7yp8fnJA6n4uf-fCAqT1SFM6lPwRA',
    appId: '1:558171062775:ios:1158ddbf75631a898f2ef2',
    messagingSenderId: '558171062775',
    projectId: 'quickhub-f3b02',
    storageBucket: 'quickhub-f3b02.firebasestorage.app',
    iosBundleId: 'com.example.quickHubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4EK7yp8fnJA6n4uf-fCAqT1SFM6lPwRA',
    appId: '1:558171062775:ios:1158ddbf75631a898f2ef2',
    messagingSenderId: '558171062775',
    projectId: 'quickhub-f3b02',
    storageBucket: 'quickhub-f3b02.firebasestorage.app',
    iosBundleId: 'com.example.quickHubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwQdW5JSkuGCCzq-2g0Y4GtRcw_nDLKk',
    appId: '1:558171062775:web:3223cb90018cb70a8f2ef2',
    messagingSenderId: '558171062775',
    projectId: 'quickhub-f3b02',
    authDomain: 'quickhub-f3b02.firebaseapp.com',
    storageBucket: 'quickhub-f3b02.firebasestorage.app',
    measurementId: 'G-19KQZ85E72',
  );
}
